### ISSUE TITLE
Error if domain can't be found

### ISSUE THREAD

**Issue by Xitro01** [indianajson/cloudfish#2]
There is an error if a domain can't be found:
```
Traceback (most recent call last):
  File "/home/kali/Tools/cloudfish/cloudfish.py", line 149, in <module>
    records = dns.records(args.domain,args.key,args.email,args.account,verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Tools/cloudfish/cloudfish.py", line 74, in records
    self.zone = create_j["result"]["id"]
                ~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
Would be nicer to show an error message, that the domain could not be found.

**Comment by indianajson** [comment]
You are totally right. My error handling back then was pretty poor. 😬 I'm super busy at the moment but if you want to write up a patch feel free to submit it as a pull request.

**Comment by indianajson** [comment]
Pull request accepted, apologies again for the delay on my end to accept it.
